-- Morning briefing (PB-campaign wave 1). A second daily coach message, kind
-- 'morning', mirroring the evening review: one per London day, delivered to
-- Telegram. Generated by /api/coach/morning once the overnight wellness (sleep /
-- HRV) has synced from intervals.icu, with a configurable fallback send time.

-- One morning briefing per London day — the partial unique index that makes the
-- generator idempotent (a concurrent fire hits 23505 and skips), mirroring
-- coach_messages_evening_per_day.
CREATE UNIQUE INDEX IF NOT EXISTS coach_messages_morning_per_day
  ON public.coach_messages (for_date) WHERE (kind = 'morning');

-- Morning-briefing preferences, alongside the coach autonomy/guardrails.
ALTER TABLE coaching_prefs
  ADD COLUMN IF NOT EXISTS morning_briefing      boolean NOT NULL DEFAULT true,   -- send a morning briefing at all
  ADD COLUMN IF NOT EXISTS morning_fallback_time text    NOT NULL DEFAULT '09:30', -- London HH:MM; send even if wellness hasn't landed by then
  ADD COLUMN IF NOT EXISTS morning_skip_rest     boolean NOT NULL DEFAULT false;  -- skip on days with no training
