-- Race priority (A/B/C) on race sessions, and a table of additional future
-- race plans rendered as their own A-race block at the bottom of the Plan page.
ALTER TABLE plan_sessions ADD COLUMN IF NOT EXISTS priority text;

UPDATE plan_sessions SET priority = 'C' WHERE name = 'LC 3k';
UPDATE plan_sessions SET priority = 'B' WHERE name = 'Porthcawl 10km';
UPDATE plan_sessions SET priority = 'A' WHERE name = 'Dragon 50 Ultra';

CREATE TABLE IF NOT EXISTS plans (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  slug        text,
  race_date   date NOT NULL,
  distance_km numeric,
  target_time text,
  target_pace text,
  sort_order  integer NOT NULL DEFAULT 0
);
ALTER TABLE plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_all" ON plans FOR ALL TO authenticated USING (true) WITH CHECK (true);

INSERT INTO plans (name, slug, race_date, distance_km, sort_order) VALUES
  ('Malaga Marathon', 'malaga-marathon', '2026-11-08', 42.2, 1);
